stages:
  - test
  - build

test-runner:
  stage: test
  script:
    - echo "Runner is working!"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_IMAGE_LOCATION/kit-runtime:latest" .
    - docker push "$CI_IMAGE_LOCATION/kit-runtime:latest"
